{% set name = "squirrel-datasets-core" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_datasets_core-{{ version }}.tar.gz
  sha256: 27eebf25f1fb11e07cfc66d030d3f9668d5907d27be0216d35bf84170cd9278d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - docutils >=0.17.1,<1.0
    - fire >=0.4.0,<1.0
    - pillow >=9.4.0,<10.0
    - scipy >=1.9.3,<2.0
    - squirrel-core >=0.19.0,<1.0
    - datasets >=2.9.0,<3.0
    - pyspark >=3.2.2,<4.0
    - torchvision >=0.14.1,<1.0

test:
  imports:
    - squirrel_datasets_core
    - squirrel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-datasets-core/
  summary: Squirrel public datasets collection.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - winfried-ripken
    - AlirezaSohofi
    - maik-schmidt
    - hosseinkarjoo
