{% set name = "squirrel-datasets-core" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_datasets_core-{{ version }}.tar.gz
  sha256: 8f62d9152bf17e6380901cfdf68a53ce3b1954ea3583043a2c78451f0986b488

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - datasets
    - squirrel-core >=0.12.1
    - numpy
    - pillow
    - pytorch
    - torchvision
    - pyspark >=3.2.0
    - hydra-core >=1.1.0
    - hub
    - docutils
    - fire
    - scipy


test:
  imports:
    - squirrel_datasets_core
    - squirrel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-datasets-core/
  summary: Squirrel public datasets collection.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
