{% set name = "squirrel-datasets-core" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_datasets_core-{{ version }}.tar.gz
  sha256: bd0fef3c7a89163a0bbff359a220f85101f13d809b97a230e98db4808e0c398f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - datasets
    - squirrel-core >=0.12.1
    - dill >=0.3.5.1
    - numpy
    - pillow
    - pytorch
    - torchvision
    - pyspark >=3.2.0
    - hub
    - docutils
    - fire
    - scipy

test:
  imports:
    - squirrel_datasets_core
    - squirrel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-datasets-core/
  summary: Squirrel public datasets collection.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - winfried-ripken
    - AlirezaSohofi
