{% set name = "squirrel-datasets-core" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_datasets_core-{{ version }}.tar.gz
  sha256: 7d22c05101bd40a0e7d8c668dc31d3590441349321ba0aa77a15de8fab534585

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - datasets
    - squirrel-core >=0.12.1
    - dill >=0.3.5.1
    - numpy
    - pillow
    - pytorch
    - torchvision
    - pyspark >=3.2.0
    - hub
    - docutils
    - fire
    - scipy

test:
  imports:
    - squirrel_datasets_core
    - squirrel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-datasets-core/
  summary: Squirrel public datasets collection.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - winfried-ripken
    - AlirezaSohofi
    - maik-schmidt
    - hosseinkarjoo
