{% set name = "squirrel-datasets-core" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_datasets_core-{{ version }}.tar.gz
  sha256: 6889955eca43984940b7049c691adebc8e17bde302fb08b5b253530d33fee58f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - squirrel-core

test:
  imports:
    - squirrel_datasets_core
    - squirrel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-datasets-core/
  summary: Squirrel public datasets collection.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
